fix(actions): correct job failure evaluation and add log output

diff --git a/.github/actions/run-dash/action.yaml b/.github/actions/run-dash/action.yaml
--- a/.github/actions/run-dash/action.yaml
+++ b/.github/actions/run-dash/action.yaml
@@ -116,11 +116,22 @@ runs:
     - name: Verify job status
       run: |
         echo "Verify step outputs and action input to let the job pass/fail"
-        if [[ (${{ inputs.fail_on_out_of_date == 'true' }} && ${{ steps.dependency-diff.outputs.changed == 'true' }} && echo "up-to-date check OK") || \
-              (${{ inputs.fail_on_rejected == 'true' }} && ${{ steps.rejected-check.outputs.rejected-found == 'true' }} && echo "rejected check OK") || \
-              (${{ inputs.fail_on_restricted == 'true' }} && ${{ steps.restricted-check.outputs.restricted-found == 'true' }} && echo "restricted check OK") \
-        ]]; then
-          echo "A check, that is marked as failure relevant, has not passed. Failing job."
-          exit 1
+        if [[  "${{ inputs.fail_on_out_of_date }}" == "true" ]]; then
+          if [[ "${{ steps.dependency-diff.outputs.changed }}" == "true" ]]; then
+            echo "Dependencies are out of date. Failing check!"
+            exit 1
+          fi
+        fi
+        if [[ "${{ inputs.fail_on_rejected }}" == "true" ]]; then
+          if [[ "${{ steps.rejected-check.outputs.rejected-found }}" == "true" ]]; then
+            echo "Rejected dependencies found. Failing check!"
+            exit 1
+          fi
+        fi
+        if [[ "${{ inputs.fail_on_restricted }}" == "true" ]]; then
+          if [[ "${{ steps.restricted-check.outputs.restricted-found }}" == "true" ]]; then
+            echo "Restricted libraries found. Failing check!"
+            exit 1
+          fi
         fi
       shell: bash
